services:
  dvfl-home-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: DVFL_home_dev
    ports:
      - "3000:3000"
  
  dvfl-home-prod:
    image: ghcr.io/devinci-fablab/dvfl-home:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    security_opt:
      - no-new-privileges:true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dvfl-home.rule=Host(`devinci-fablab.fr`)'
      - 'traefik.http.routers.dvfl-home.entrypoints=websecure'
      - 'traefik.http.routers.dvfl-home.tls.certresolver=myresolver'
      - 'traefik.http.services.dvfl-home.loadbalancer.server.port=3000'
      - 'com.centurylinklabs.watchtower.enable=true'
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
