version: "3"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: DVFL_home
    expose:
      - "3000"
    networks:
      network:
        ipv4_address: ${FRONT_IP}

networks:
  network:
    driver: bridge
    ipam:
     config:
       - subnet: ${SUBNET}
         gateway: ${GATEWAY}
